### PR TITLE
Mostly re-wrote the crate.

### PR DESCRIPTION
**Pull request by ghost**
I'm not sure why the old `pad` function returned the provided mutable reference, I will re-add it if necessary.

### CODE REVIEW

**Comment by jeffcarp** [comment]
Hey thanks! Why not publish your own crate though?

**Comment by ghost** [comment]
You own the crate name.

**Comment by ghost** [comment]
Your crate also did not pad octet strings whose length was a multiple of the block size correctly.

**Comment by ghost** [comment]
Is there something wrong with this PR?

**Comment by jeffcarp** [comment]
@cedenday no, I will land this and push when I get the time

**Comment by jeffcarp** [comment]
Thanks! I added you to the authors in [`Cargo.toml`](https://github.com/jeffcarp/pkcs7/blob/master/Cargo.toml) and published this as [version 1.0.0](https://crates.io/crates/pkcs7).

**Pull request merged**
